FROM python:3.9-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier le fichier de dépendances
COPY requirements.txt .

# Installer les dépendances du frontend
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copier le reste des fichiers
COPY . .

